In [1]:
# =====================================================================
# STEP 1: IMPORT NECESSARY LIBRARIES
# =====================================================================
import numpy as np
from scipy.sparse import csr_matrix
# Importing all key graph algorithms from the Compressed Sparse Graph submodule [00:01:29]
from scipy.sparse.csgraph import (
    connected_components,
    dijkstra,
    floyd_warshall,
    bellman_ford,
    depth_first_order,
    breadth_first_order
)

print("="*60)
print("             SCIPY GRAPH ALGORITHMS DEMONSTRATION            ")
print("="*60)

# =====================================================================
# STEP 2: CONNECTED COMPONENTS ANALYSIS [00:04:40]
# =====================================================================
print("\n--- SECTION 1: CONNECTED COMPONENTS ---")

# Define an adjacency matrix matching the video's example [00:07:35]
graph_array = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

# Convert the array to a CSR Matrix format [00:08:52]
graph_csr = csr_matrix(graph_array)

# Find the connected components inside the graph [00:09:05]
n_components, labels = connected_components(graph_csr)
print(f"1. Total Number of Connected Components: {n_components}")
print(f"2. Component Labels for Vertices: {labels}")


# =====================================================================
# STEP 3: SHORTEST PATH ALGORITHMS (DIJKSTRA & FLOYD-WARSHALL) [00:10:08]
# =====================================================================
print("\n" + "="*60)
print("--- SECTION 2: SHORTEST PATHS ---")

# Execute Dijkstra's algorithm from index node 0 [00:16:09]
dijkstra_dist, predecessors = dijkstra(graph_csr, return_predecessors=True, indices=0)
print("1. Dijkstra Shortest Distance Array (from Node 0):")
print(dijkstra_dist)

# Execute Floyd-Warshall to get all-pairs shortest paths [00:19:54]
fw_matrix = floyd_warshall(graph_csr, return_predecessors=False)
print("\n2. Floyd-Warshall All-Pairs Shortest Path Matrix:")
print(fw_matrix)


# =====================================================================
# STEP 4: BELLMAN-FORD (HANDLING NEGATIVE WEIGHTS) [00:22:42]
# =====================================================================
print("\n" + "="*60)
print("--- SECTION 3: NEGATIVE WEIGHTS HANDLING ---")

# Create a graph containing a negative weight entry (-1) [00:24:02]
graph_neg_weight = np.array([
    [0, -1, 2],
    [1,  0, 0],
    [2,  0, 0]
])
graph_neg_csr = csr_matrix(graph_neg_weight)

# Execute Bellman-Ford algorithm from index node 0 [00:24:20]
bf_dist, bf_pred = bellman_ford(graph_neg_csr, return_predecessors=True, indices=0)
print("1. Bellman-Ford Shortest Distance with Negative Edges:")
print(bf_dist)


# =====================================================================
# STEP 5: GRAPH TRAVERSALS (DFS vs BFS) [00:26:00]
# =====================================================================
print("\n" + "="*60)
print("--- SECTION 4: TRAVERSALS (DFS vs BFS) ---")

# Construct a graph layout specifically for traversal testing [00:28:14]
traversal_array = np.array([
    [0, 1, 0, 1],
    [1, 0, 1, 1],
    [0, 1, 0, 0],
    [1, 1, 0, 0]
])
traversal_csr = csr_matrix(traversal_array)

# Compute Depth-First Search order starting from node 0 [00:29:22]
dfs_nodes, dfs_predecessors = depth_first_order(traversal_csr, i_start=0)
print("1. Depth-First Search (DFS) Traversal Node Order:")
print(dfs_nodes)

# Compute Breadth-First Search order starting from node 0 [00:32:05]
bfs_nodes, bfs_predecessors = breadth_first_order(traversal_csr, i_start=0)
print("\n2. Breadth-First Search (BFS) Traversal Node Order:")
print(bfs_nodes)

print("\n" + "="*60)
print("Graph Operations Successfully Executed in Colab Space.")
print("="*60)

             SCIPY GRAPH ALGORITHMS DEMONSTRATION            

--- SECTION 1: CONNECTED COMPONENTS ---
1. Total Number of Connected Components: 1
2. Component Labels for Vertices: [0 0 0]

--- SECTION 2: SHORTEST PATHS ---
1. Dijkstra Shortest Distance Array (from Node 0):
[0. 1. 2.]

2. Floyd-Warshall All-Pairs Shortest Path Matrix:
[[0. 1. 2.]
 [1. 0. 3.]
 [2. 3. 0.]]

--- SECTION 3: NEGATIVE WEIGHTS HANDLING ---
1. Bellman-Ford Shortest Distance with Negative Edges:
[ 0. -1.  2.]

--- SECTION 4: TRAVERSALS (DFS vs BFS) ---
1. Depth-First Search (DFS) Traversal Node Order:
[0 1 2 3]

2. Breadth-First Search (BFS) Traversal Node Order:
[0 1 3 2]

Graph Operations Successfully Executed in Colab Space.
